# Generated by Django 4.2 on 2023-05-23 09:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categorie',
            fields=[
                ('id_categorie', models.AutoField(primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=50, verbose_name='Nom de la catégorie')),
            ],
        ),
        migrations.CreateModel(
            name='Jeux',
            fields=[
                ('id_jeux', models.AutoField(primary_key=True, serialize=False)),
                ('label', models.CharField(max_length=50, verbose_name='Nom du jeu')),
                ('img_url', models.CharField(max_length=255, verbose_name='Url image')),
                ('prix', models.FloatField(verbose_name='Prix du jeu')),
            ],
        ),
        migrations.CreateModel(
            name='Selection',
            fields=[
                ('id_selection', models.AutoField(primary_key=True, serialize=False)),
                ('titre', models.CharField(max_length=50, verbose_name='Titre de la sélection')),
            ],
        ),
        migrations.CreateModel(
            name='Posseder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categorie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appliprojet.categorie')),
                ('jeux', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appliprojet.jeux')),
            ],
        ),
        migrations.AddField(
            model_name='jeux',
            name='selection',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appliprojet.selection'),
        ),
    ]
